### Shallow Learning classes created in case developer wishes to build his or her own models, currently only the sci-kit learning prototypes are supported. 

In [1]:
import sys
sys.path.insert(0, '../')



In [2]:
from src.Utils import load_data
from src.Trainer import shallow_model_trainer

Using TensorFlow backend.


In [3]:
x_tensor, x, y_tensor, y = load_data()

In [4]:
from models.ShallowLearning.RandomForest import RandomForest
from models.ShallowLearning.KNearestNeighbors import KNN
from models.ShallowLearning.SupportVectorMachine import SVM
from models.ShallowLearning.LogisticRegression import LogRegress
from models.ShallowLearning.NaiveBayes import GaussianNaiveBayes, MultinomialNaiveBayes, BernoulliNaiveBayes

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import normalize

import numpy as np

In [5]:
x_n = normalize(x)
x_tensor_n = normalize(x_tensor, axis = 0)

In [6]:
x_n

array([[3.81386314e-06, 9.99781338e-01, 1.43019868e-02, 1.52554525e-02,
        3.81386314e-06, 1.90693157e-06],
       [1.28036699e-03, 2.56073399e-04, 6.40183497e-01, 7.68220197e-01,
        1.02429360e-03, 2.56073399e-04],
       [2.73576434e-04, 9.11921448e-05, 6.83941086e-01, 7.29537159e-01,
        1.82384290e-04, 9.11921448e-05],
       ...,
       [1.78883936e-03, 8.94419678e-04, 4.47209839e-01, 8.94419678e-01,
        3.57767871e-03, 0.00000000e+00],
       [4.57697071e-05, 9.99854507e-01, 7.62828451e-03, 1.52565690e-02,
        9.15394141e-05, 0.00000000e+00],
       [1.69484038e-09, 1.00000000e+00, 6.35565142e-06, 6.77936151e-06,
        4.23710095e-09, 0.00000000e+00]])

In [11]:
x_tensor.shape[1]

6

In [ ]:
524288 / 847288609443


In [8]:
"""Control Data for debugging, ignore"""
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
from sklearn.decomposition import PCA

# import some data to play with
iris = datasets.load_iris()
X = iris.data[:, :2]  # we only take the first two features.
Y = iris.target

In [7]:
# Shallow Models with default params
gb = GaussianNaiveBayes()
mb = MultinomialNaiveBayes()
bern_bb = BernoulliNaiveBayes()
knn = KNN(num_neighbors=5)
rlf = RandomForest() 
log_lf = LogRegress() 
slf = SVM(c_penalty='l2',s_kernel='rbf', s_degree=5, s_kernel_cache_size=1024, s_tolerance=.001, s_class_weight=None,s_gamma = 'auto')

In [13]:
# trained_model = shallow_model.train(x,y)
rlf_scores = cross_val_score(rlf.model, x_n, y, cv=10)
log_reg_scores =cross_val_score(log_lf.model,x_n,y,cv=10)
knn_scores = cross_val_score(knn.model,x_n,y,cv=10)

In [12]:
# Gaussian NB
# gaussian_nb_scores = cross_val_score(gb.model, x_n,y,cv=10)
# multinomial_nb_scores = cross_val_score(mb.model,x_n,y,cv=10)
bernouli_nb_scores = cross_val_score(bern_bb.model,x_n,y,cv=10)

In [14]:
# Random Forest Scores
rlf_scores

array([0.93961686, 0.94159385, 0.95634476, 0.96127418, 0.9623931 ,
       0.95959219, 0.90118385, 0.95604437, 0.95189902, 0.89696381])

In [17]:
np.mean(rlf_scores)

0.9426905984743827

In [18]:
log_reg_scores

array([0.79424176, 0.79307641, 0.79307641, 0.79307641, 0.79306868,
       0.79306868, 0.79306868, 0.79306868, 0.79306868, 0.79306868])

In [19]:
np.mean(log_reg_scores)

0.7931883044675236

In [ ]:
slf_scores = cross_val_score(slf.model, x_n, y, cv=10)

In [12]:
slf_scores

array([0.66666667, 0.8       , 0.86666667, 0.86666667, 0.8       ,
       0.66666667, 0.86666667, 0.86666667, 0.86666667, 0.86666667])

In [21]:
# High accuracy could reveal some localization properties
knn_scores

array([0.99880503, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [22]:
np.mean(knn_scores) # WTF

0.9998805033795138

In [10]:
gaussian_nb_scores

array([0.59684828, 0.59500336, 0.62745537, 0.63350512, 0.64559137,
       0.64167009, 0.6411846 , 0.64342533, 0.63726332, 0.63308063])

In [13]:
np.mean(gaussian_nb_scores)

0.6295027461612421

In [14]:
bernouli_nb_scores

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.mean(bernouli_nb_scores) # Doubld wtf

1.0